BEGIN;

CREATE TABLE IF NOT EXISTS product (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    price INTEGER NOT NULL,
    active INTEGER NOT NULL DEFAULT 1
);

ALTER TABLE product ADD COLUMN unit TEXT DEFAULT 'pz';
ALTER TABLE product ADD COLUMN allow_decimal INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_product_active ON product(active);
CREATE INDEX IF NOT EXISTS idx_product_name ON product(name);

COMMIT;

